import 'package:my_cart/model/list_model.dart';

class ComList{

  static List<ListModel> names = [
    ListModel(name: 'Apple', price: 99, quantity: 1),
    ListModel(name: 'Banana', price: 49, quantity: 1),
    ListModel(name: 'Orange', price: 79, quantity: 1),
    ListModel(name: 'Grapes', price: 59, quantity: 1),
    ListModel(name: 'Mango', price: 89, quantity: 1),
    ListModel(name: 'Pineapple', price: 149, quantity: 1),
    ListModel(name: 'Strawberry', price: 199, quantity: 1),
    ListModel(name: 'Watermelon', price: 39, quantity: 1),
    ListModel(name: 'Blueberry', price: 229, quantity: 1),
    ListModel(name: 'Peach', price: 109, quantity: 1),
    ListModel(name: 'Pear', price: 69, quantity: 1),
    ListModel(name: 'Cherry', price: 259, quantity: 1),
    ListModel(name: 'Kiwi', price: 149, quantity: 1),
    ListModel(name: 'Papaya', price: 99, quantity: 1),
    ListModel(name: 'Lemon', price: 29, quantity: 1),
    ListModel(name: 'Avocado', price: 189, quantity: 1),
    ListModel(name: 'Pomegranate', price: 119, quantity: 1),
    ListModel(name: 'Lychee', price: 149, quantity: 1),
    ListModel(name: 'Plum', price: 79, quantity: 1),
    ListModel(name: 'Apricot', price: 99, quantity: 1),
    ListModel(name: 'Blackberry', price: 299, quantity: 1),
    ListModel(name: 'Raspberry', price: 279, quantity: 1),
    ListModel(name: 'Cantaloupe', price: 49, quantity: 1),
    ListModel(name: 'Coconut', price: 89, quantity: 1),
    ListModel(name: 'Fig', price: 179, quantity: 1),
    ListModel(name: 'Guava', price: 59, quantity: 1),
    ListModel(name: 'Jackfruit', price: 99, quantity: 1),
    ListModel(name: 'Lime', price: 39, quantity: 1),
    ListModel(name: 'Mandarin', price: 79, quantity: 1),
    ListModel(name: 'Nectarine', price: 89, quantity: 1),
    ListModel(name: 'Passion Fruit', price: 199, quantity: 1),
    ListModel(name: 'Cranberry', price: 249, quantity: 1),
    ListModel(name: 'Durian', price: 299, quantity: 1),
    ListModel(name: 'Dragon Fruit', price: 159, quantity: 1),
    ListModel(name: 'Gooseberry', price: 139, quantity: 1),
    ListModel(name: 'Mulberry', price: 179, quantity: 1),
    ListModel(name: 'Persimmon', price: 119, quantity: 1),
    ListModel(name: 'Starfruit', price: 149, quantity: 1),
    ListModel(name: 'Tangerine', price: 59, quantity: 1),
    ListModel(name: 'Ugli Fruit', price: 129, quantity: 1),
    ListModel(name: 'Pomelo', price: 199, quantity: 1),
    ListModel(name: 'Quince', price: 109, quantity: 1),
    ListModel(name: 'Soursop', price: 189, quantity: 1),
    ListModel(name: 'Tamarillo', price: 169, quantity: 1),
    ListModel(name: 'Yuzu', price: 299, quantity: 1),
  ];


}